stages:
  - test
  - sync

variables:
  GIT_STRATEGY: none

test-sync:
  stage: test
  image: alpine/git:latest
    
  script:
    - echo "Testing CI configuration ..."
    - echo "Testing CI configuration (MR validation)..."
    - test -n "$GITHUB_DEPLOY_TOKEN" || (echo "ERROR GITHUB_DEPLOY_TOKEN is not set" && exit 1)
    - apk add --no-cache python3 py3-pip
    - pip3 install git-filter-repo
    - git config --global user.email "support@enrichlayer.com"
    - git config --global user.name "Enrich Layer"
    - git clone --mirror ${CI_REPOSITORY_URL} repo-mirror
    - cd repo-mirror
    - git filter-repo --force --commit-callback 'commit.author_name = b"Enrich Layer"; commit.author_email = b"support@enrichlayer.com"; commit.committer_name = b"Enrich Layer"; commit.committer_email = b"support@enrichlayer.com"'
    - echo "Rewrite successful. Sample commits:"
    - git log --oneline -5 --pretty=format:"%h %an <%ae> %s"
    - git remote add github https://${GITHUB_DEPLOY_TOKEN}@github.com/enrichlayer/enrichlayer-api.git
    - echo "Testing connection to GitHub..."
    - git ls-remote github HEAD
    - echo "Connection test successful - ready to sync"
    - echo "Note MR pipelines do NOT sync to GitHub"

  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "test-ci"

sync-to-github:
  needs: test-sync
  stage: sync
  image: alpine/git:latest
   
  script:
    - echo "Syncing to GitHub branch ${CI_COMMIT_BRANCH}..."
    - test -n "$GITHUB_DEPLOY_TOKEN" || (echo "ERROR GITHUB_DEPLOY_TOKEN is not set" && exit 1)
    - apk add --no-cache python3 py3-pip
    - pip3 install git-filter-repo
    - git config --global user.email "support@enrichlayer.com"
    - git config --global user.name "Enrich Layer"
    - git clone --mirror ${CI_REPOSITORY_URL} repo-mirror
    - cd repo-mirror
    - git filter-repo --force --commit-callback 'commit.author_name = b"Enrich Layer"; commit.author_email = b"support@enrichlayer.com"; commit.committer_name = b"Enrich Layer"; commit.committer_email = b"support@enrichlayer.com"'
    - git remote add github https://${GITHUB_DEPLOY_TOKEN}@github.com/enrichlayer/enrichlayer-api.git
    - echo "Starting sync to GitHub..."
    - git push github --mirror --force
    - echo "Verifying sync..."
    - echo "Current branch ${CI_COMMIT_BRANCH}"
    - echo "GitLab HEAD commit:"
    - git log -1 --pretty=format:"%h %an <%ae> %s"
    - echo "GitHub branches:"
    - git ls-remote github "refs/heads/*" | cut -f2 | cut -d'/' -f3
    - git rev-list --all --count | xargs -I {} echo "Total commits synced {}"
    - echo "Successfully synced to GitHub"
  
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "test-ci"
 